# -*- coding: utf-8 -*-
"""computer_eng_salaryprediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C4xGWd3jYCNgAg3VDSpVuiXR7ybdDxVs
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings

data=pd.read_csv("/content/Engineering_graduate_salary.csv")

data.head()

data.columns.values

data.shape

data.isnull().sum()

y=data.Salary
x=data[["Gender","CollegeTier","Degree","collegeGPA","ComputerProgramming","extraversion","openess_to_experience"]]

columns=x.columns.to_list()

for i in range(len(columns)):
  plt.subplots(figsize=(3,3))
  sns.histplot(data=data,x=columns[i],kde=True)

#lets check skewness

from scipy.stats import skew

numeric_columns = x.select_dtypes(include="number")
numeric_columns["Salary"]=y

numeric_columns=numeric_columns.columns

print("skewness of the data:")
skewnes=[]
for i in range(len(numeric_columns)):
  column=numeric_columns[i]
  skewnes.append((column,skew(data[column])))
skewnes.sort(key= lambda x:abs(x[1]), reverse=True)
print(skewnes)



#tier is categorical but we should transform other numeric skewed columns.

from sklearn.preprocessing import PowerTransformer, RobustScaler

robust=RobustScaler()
power=PowerTransformer()

x.openess_to_experience=power.fit_transform(x[['openess_to_experience']])
x.collegeGPA=robust.fit_transform(x[["collegeGPA"]])

numeric_data=x.select_dtypes(include="number")


corr=numeric_data.corr()

sns.heatmap(data=corr,annot=True,cmap="coolwarm")

x=pd.get_dummies(x,columns=["Gender","Degree"],drop_first=True)

x.head()

#lets transform target value

y_log = np.log1p(y)

from sklearn.linear_model import LinearRegression

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()



from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y_log,test_size=0.2,random_state=3)




from sklearn.preprocessing import StandardScaler

numeric_cols = x_train.select_dtypes(include="number").columns

scaler = StandardScaler()

# SADECE train'de fit
x_train[numeric_cols] = scaler.fit_transform(x_train[numeric_cols])

# test'te sadece transform
x_test[numeric_cols] = scaler.transform(x_test[numeric_cols])

lin=LinearRegression()

lin.fit(x_train,y_train)

x_train

y_pred_train=lin.predict(x_train)
y_pred_test  = lin.predict(x_test)

print("Train R2:", r2_score(y_train, y_pred_train))
print("Test  R2:", r2_score(y_test, y_pred_test))
print("Test MAE:", mean_absolute_error(y_test, y_pred_test))
print("Test MSE:", mean_squared_error(y_test, y_pred_test))

"""## PREDICTIVE SYSTEM

------------------------------
Another version
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PowerTransformer, RobustScaler, StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

y = data["Salary"]
X = data[["Gender","CollegeTier","Degree","collegeGPA","ComputerProgramming","extraversion","openess_to_experience"]]
y_log = np.log1p(y)

X_train, X_test, y_train, y_test = train_test_split(
    X, y_log, test_size=0.2, random_state=3
)

numeric_features = ["CollegeTier","collegeGPA","ComputerProgramming","extraversion","openess_to_experience"]
categorical_features = ["Gender","Degree"]

numeric_transformer = Pipeline(steps=[
    ("power", PowerTransformer()),
    ("scaler", StandardScaler())
])

categorical_transformer = OneHotEncoder(drop="first", handle_unknown="ignore")

preprocess = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features),
    ],
    remainder="drop"
)

model = Pipeline(steps=[
    ("prep", preprocess),
    ("lin", LinearRegression())
])

model.fit(X_train, y_train)

y_pred_train = model.predict(X_train)
y_pred_test  = model.predict(X_test)

print("Train R2:", r2_score(y_train, y_pred_train))
print("Test  R2:", r2_score(y_test, y_pred_test))
print("Test MAE:", mean_absolute_error(y_test, y_pred_test))
print("Test MSE:", mean_squared_error(y_test, y_pred_test))

res=model.predict(pd.DataFrame([{
    "Gender": "m",
    "Degree": "B.Tech/B.E.",
    "CollegeTier": 2,
    "collegeGPA": 73.82,
    "ComputerProgramming": 485,
    "extraversion": 1.2396,
    "openess_to_experience": -0.2889
}]))
print(res)

